/*
 * Stream Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v71.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

/// UserObjectRequest : Represents chat user

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserObjectRequest {
    /// Expiration date of the ban
    #[serde(rename = "ban_expires", skip_serializing_if = "Option::is_none")]
    pub ban_expires: Option<String>,
    /// Whether a user is banned or not
    #[serde(rename = "banned", skip_serializing_if = "Option::is_none")]
    pub banned: Option<bool>,
    /// Unique user identifier
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "invisible", skip_serializing_if = "Option::is_none")]
    pub invisible: Option<bool>,
    /// Preferred language of a user
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    /// Revocation date for tokens
    #[serde(
        rename = "revoke_tokens_issued_before",
        skip_serializing_if = "Option::is_none"
    )]
    pub revoke_tokens_issued_before: Option<String>,
    /// Determines the set of user permissions
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    /// List of teams user is a part of
    #[serde(rename = "teams", skip_serializing_if = "Option::is_none")]
    pub teams: Option<Vec<String>>,
}

impl UserObjectRequest {
    /// Represents chat user
    pub fn new(id: String) -> UserObjectRequest {
        UserObjectRequest {
            ban_expires: None,
            banned: None,
            id,
            invisible: None,
            language: None,
            revoke_tokens_issued_before: None,
            role: None,
            teams: None,
        }
    }
}
